# Generated by Django 4.0.1 on 2022-01-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
