# Generated by Django 4.0.1 on 2022-01-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps_app', '0002_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_score', models.IntegerField(default=0)),
                ('System_score', models.IntegerField(default=0)),
            ],
        ),
    ]
